name: CICD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
  
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  security-check:
    runs-on: self-hosted
    needs: compile

    steps:
    - uses: actions/checkout@v4
    
    - name: Trivy FS scan
      run: trivy fs --format table  -o fs-report.json .
   
    - name: gileaks codescan
      run: gitleaks detect source.  -r gitleaks-report.json -f json

  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
  
    - name: Unit test cases
      run: mvn test

  Build_Sonar_scan:
    runs-on: self-hosted
    needs: test

    steps:
    - uses: actions/checkout@v4
  
    - name: Build project
      run: mvn package

    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.2.0 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        pollingTimeoutSec: 600
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 
      

      
    
    
  
